---
- name: create systemd service unit
  template:
    src: domain_exporter.service.j2
    dest: /etc/systemd/system/domain_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart domain exporter
