---
- name: create domain_exporter system group
  group:
    name: domain-exp
    system: true
    state: present

- name: create domain_exporter system user
  user:
    name: domain-exp
    system: true
    shell: "/usr/sbin/nologin"
    group: domain-exp
    createhome: false

- name: download domain exporter binary to local folder
  become: false
  unarchive:
    src: "https://github.com/caarlos0/domain_exporter/releases/download/v{{ domain_exporter_version }}/domain_exporter_linux_{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
    dest: "/tmp"
    remote_src: true
    creates: "/tmp/domain_exporter-{{ domain_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/domain_exporter"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false

- name: propagate domain exporter binary
  copy:
    src: "/tmp/domain_exporter-{{ domain_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/domain_exporter"
    dest: "/usr/local/bin/domain_exporter"
    mode: 0750
    owner: domain-exp
    group: domain-exp
  notify:
    - restart domain exporter

# - name: Install libcap on Debian systems
#   package:
#     name: "libcap2-bin"
#     state: present
#   register: _download_packages
#   until: _download_packages is succeeded
#   retries: 5
#   delay: 2
#   when: ansible_os_family | lower == "debian"

- name: Ensure domain exporter binary has cap_net_raw capability
  capabilities:
    path: '/usr/local/bin/domain_exporter'
    capability: cap_net_raw+ep
    state: present
