---
- include: preflight.yml
  tags:
    - domain_exporter_install
    - domain_exporter_configure
    - domain_exporter_run

- include: install.yml
  become: true
  tags:
    - domain_exporter_install

- include: configure.yml
  become: true
  tags:
    - domain_exporter_configure

- name: ensure domain_exporter service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: domain_exporter
    state: started
    enabled: true
  tags:
    - domain_exporter_run
