---
- name: restart domain exporter
  become: true
  systemd:
    daemon_reload: true
    name: domain_exporter
    state: restarted

- name: reload domain exporter
  become: true
  systemd:
    name: domain_exporter
    state: reloaded
